# permissions for end users to edit alertnotitficationtargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertnotitficationtarget-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubesla
    app.kubernetes.io/part-of: kubesla
    app.kubernetes.io/managed-by: kustomize
  name: alertnotitficationtarget-editor-role
rules:
- apiGroups:
  - openslo.kubesla.com
  resources:
  - alertnotitficationtargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openslo.kubesla.com
  resources:
  - alertnotitficationtargets/status
  verbs:
  - get
