apiVersion: openslo.kubesla.com/v1alpha1
kind: Datasource
metadata:
  namespace: default
  labels:
    app.kubernetes.io/name: datasource
    app.kubernetes.io/instance: datasource-sample
    app.kubernetes.io/part-of: kubesla
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubesla
  name: datasource-sample
spec:
  displayName: Example Prometheus
  description: This is an example Prometheus data source for monitoring.
  type: Prometheus
  connectionDetails:
    url: http://prometheus-user-workload.apps.okd.cloudnative.lab
