apiVersion: openslo.kubesla.com/v1alpha1
kind: AlertNotitficationTarget
metadata:
  labels:
    app.kubernetes.io/name: alertnotitficationtarget
    app.kubernetes.io/instance: alertnotitficationtarget-sample
    app.kubernetes.io/part-of: kubesla
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubesla
  name: alertnotitficationtarget-sample
spec:
  # TODO(user): Add fields here
